-- MySQL Workbench Synchronization
-- Generated: 2021-01-20 13:30
-- Model: New Model
-- Version: 1.1
-- Project: HOTMART CHALLENGE - BACK-END
-- Author: Daniel Augusto

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `hotmart_challenge`.`SALE` 
DROP FOREIGN KEY `SALE_BUYER_FK`;

ALTER TABLE `hotmart_challenge`.`BUYER_AUDIT` 
DROP FOREIGN KEY `BUYER_AUDIT_BUYER_FK`,
DROP FOREIGN KEY `BUYER_AUDIT_REVINFO_FK`;

ALTER TABLE `hotmart_challenge`.`PRODUCT_AUDIT` 
DROP FOREIGN KEY `PRODUCT_AUDIT_PRODUCT_FK`,
DROP FOREIGN KEY `PRODUCT_AUDIT_REVINFO_FK`;

ALTER TABLE `hotmart_challenge`.`SALE_AUDIT` 
DROP FOREIGN KEY `SALE_AUDIT_BUYER_FK`,
DROP FOREIGN KEY `SALE_AUDIT_REVINFO_FK`;

ALTER TABLE `hotmart_challenge`.`PRODUCT_CATEGORY_AUDIT` 
DROP FOREIGN KEY `PRODUCT_CATEGORY_AUDIT_PRODUCT_CATEGORY_FK`,
DROP FOREIGN KEY `PRODUCT_CATEGORY_AUDIT_REFINFO_FK`;

ALTER TABLE `hotmart_challenge`.`SALESMAN_AUDIT` 
DROP FOREIGN KEY `SALESMAN_AUDIT_REVINFO_FK`;

ALTER TABLE `hotmart_challenge`.`PRODUCT` 
ADD COLUMN `ID_PRODUCT_CATEGORY` INT(11) NOT NULL AFTER `CREATION_DATE`,
ADD INDEX `PRODUCT_PRODUCT_CATEGORY_FK_idx` (`ID_PRODUCT_CATEGORY` ASC) VISIBLE;
;

ALTER TABLE `hotmart_challenge`.`BUYER` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `hotmart_challenge`.`SALESMAN` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `hotmart_challenge`.`PRODUCT_CATEGORY` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `hotmart_challenge`.`SALE` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `hotmart_challenge`.`BUYER_AUDIT` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `hotmart_challenge`.`PRODUCT_AUDIT` 
ADD COLUMN `ID_PRODUCT_CATEGORY` INT(11) NOT NULL AFTER `REVTYPE`,
ADD INDEX `PRODUCT_AUDIT_PRODUCT_CATEGORY_FK_idx` (`ID_PRODUCT_CATEGORY` ASC) VISIBLE;
;

ALTER TABLE `hotmart_challenge`.`SALE_AUDIT` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `hotmart_challenge`.`PRODUCT_CATEGORY_AUDIT` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `hotmart_challenge`.`SALESMAN_AUDIT` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `hotmart_challenge`.`PRODUCT` 
ADD CONSTRAINT `PRODUCT_PRODUCT_CATEGORY_FK`
  FOREIGN KEY (`ID_PRODUCT_CATEGORY`)
  REFERENCES `hotmart_challenge`.`PRODUCT_CATEGORY` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `hotmart_challenge`.`SALE` 
DROP FOREIGN KEY `SALE_SALESMAN_FK`,
DROP FOREIGN KEY `SALE_PRODUCT_FK`;

ALTER TABLE `hotmart_challenge`.`SALE` ADD CONSTRAINT `SALE_SALESMAN_FK`
  FOREIGN KEY (`ID_SALESMAN`)
  REFERENCES `hotmart_challenge`.`SALESMAN` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `SALE_PRODUCT_FK`
  FOREIGN KEY (`ID_PRODUTO`)
  REFERENCES `hotmart_challenge`.`PRODUCT` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `SALE_BUYER_FK`
  FOREIGN KEY (`ID_BUYER`)
  REFERENCES `hotmart_challenge`.`BUYER` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `hotmart_challenge`.`BUYER_AUDIT` 
ADD CONSTRAINT `BUYER_AUDIT_BUYER_FK`
  FOREIGN KEY (`ID`)
  REFERENCES `hotmart_challenge`.`BUYER` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `BUYER_AUDIT_REVINFO_FK`
  FOREIGN KEY (`rev`)
  REFERENCES `hotmart_challenge`.`REVINFO` (`REV`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `hotmart_challenge`.`PRODUCT_AUDIT` 
ADD CONSTRAINT `PRODUCT_AUDIT_PRODUCT_FK`
  FOREIGN KEY (`ID`)
  REFERENCES `hotmart_challenge`.`PRODUCT` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `PRODUCT_AUDIT_REVINFO_FK`
  FOREIGN KEY (`REV`)
  REFERENCES `hotmart_challenge`.`REVINFO` (`REV`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `PRODUCT_AUDIT_PRODUCT_CATEGORY_FK`
  FOREIGN KEY (`ID_PRODUCT_CATEGORY`)
  REFERENCES `hotmart_challenge`.`PRODUCT_CATEGORY` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `hotmart_challenge`.`SALE_AUDIT` 
DROP FOREIGN KEY `SALE_AUDIT_SALESMAN_FK`,
DROP FOREIGN KEY `SALE_AUDIT_PRODUCT_FK`,
DROP FOREIGN KEY `SALE_AUDIT_SALE_FK`;

ALTER TABLE `hotmart_challenge`.`SALE_AUDIT` ADD CONSTRAINT `SALE_AUDIT_SALESMAN_FK`
  FOREIGN KEY (`ID_SALESMAN`)
  REFERENCES `hotmart_challenge`.`SALESMAN` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `SALE_AUDIT_PRODUCT_FK`
  FOREIGN KEY (`ID_PRODUTO`)
  REFERENCES `hotmart_challenge`.`PRODUCT` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `SALE_AUDIT_BUYER_FK`
  FOREIGN KEY (`ID_BUYER`)
  REFERENCES `hotmart_challenge`.`BUYER` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `SALE_AUDIT_SALE_FK`
  FOREIGN KEY (`ID`)
  REFERENCES `hotmart_challenge`.`SALE` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `SALE_AUDIT_REVINFO_FK`
  FOREIGN KEY (`REV`)
  REFERENCES `hotmart_challenge`.`REVINFO` (`REV`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `hotmart_challenge`.`PRODUCT_CATEGORY_AUDIT` 
ADD CONSTRAINT `PRODUCT_CATEGORY_AUDIT_PRODUCT_CATEGORY_FK`
  FOREIGN KEY (`ID`)
  REFERENCES `hotmart_challenge`.`PRODUCT_CATEGORY` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `PRODUCT_CATEGORY_AUDIT_REFINFO_FK`
  FOREIGN KEY (`rev`)
  REFERENCES `hotmart_challenge`.`REVINFO` (`REV`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `hotmart_challenge`.`SALESMAN_AUDIT` 
DROP FOREIGN KEY `SALESMAN_AUDIT_SALESMAN_FK`;

ALTER TABLE `hotmart_challenge`.`SALESMAN_AUDIT` ADD CONSTRAINT `SALESMAN_AUDIT_SALESMAN_FK`
  FOREIGN KEY (`ID`)
  REFERENCES `hotmart_challenge`.`SALESMAN` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `SALESMAN_AUDIT_REVINFO_FK`
  FOREIGN KEY (`rev`)
  REFERENCES `hotmart_challenge`.`REVINFO` (`REV`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
