--CARGA INICIAL DE CATEGORIA DE PRODUTOS
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 1');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 2');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 3');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 4');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 5');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 6');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 7');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 8');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 9');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 10');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 11');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 12');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 13');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 14');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 15');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 16');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 17');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 18');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 19');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 20');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 21');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 22');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 23');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 24');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 25');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 26');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 27');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 28');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 29');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 30');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 31');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 32');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 33');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 34');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 35');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 36');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 37');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 38');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 39');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 40');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 41');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 42');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 43');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 44');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 45');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 46');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 47');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 48');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 49');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 50');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 51');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 52');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 53');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 54');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 55');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 56');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 57');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 58');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 59');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 60');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 61');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 62');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 63');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 64');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 65');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 66');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 67');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 68');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 69');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 70');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 71');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 72');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 73');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 74');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 75');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 76');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 77');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 78');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 79');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 80');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 81');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 82');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 83');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 84');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 85');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 86');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 87');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 88');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 89');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 90');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 91');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 92');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 93');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 94');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 95');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 96');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 97');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 98');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 99');
INSERT INTO `hotmart_challenge`.`product_category` (`NAME`) VALUES ('categoria 100');

--CARGA INICIAL DE PRODUTOS
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	1','descrição produto 1',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 1'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	2','descrição produto 2',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 1'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	3','descrição produto 3',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 1'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	4','descrição produto 4',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 1'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	5','descrição produto 5',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 1'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	6','descrição produto 6',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 1'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	7','descrição produto 7',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 1'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	8','descrição produto 8',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 1'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	9','descrição produto 9',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 1'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	10','descrição produto 10',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 1'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	11','descrição produto 11',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 2'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	12','descrição produto 12',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 2'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	13','descrição produto 13',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 2'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	14','descrição produto 14',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 2'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	15','descrição produto 15',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 2'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	16','descrição produto 16',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 2'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	17','descrição produto 17',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 2'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	18','descrição produto 18',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 2'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	19','descrição produto 19',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 2'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	20','descrição produto 20',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 2'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	21','descrição produto 21',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 3'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	22','descrição produto 22',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 3'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	23','descrição produto 23',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 3'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	24','descrição produto 24',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 3'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	25','descrição produto 25',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 3'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	26','descrição produto 26',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 3'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	27','descrição produto 27',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 3'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	28','descrição produto 28',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 3'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	29','descrição produto 29',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 3'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	30','descrição produto 30',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 4'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	31','descrição produto 31',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 4'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	32','descrição produto 32',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 4'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	33','descrição produto 33',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 4'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	34','descrição produto 34',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 4'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	35','descrição produto 35',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 4'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	36','descrição produto 36',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 4'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	37','descrição produto 37',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 4'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	38','descrição produto 38',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 4'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	39','descrição produto 39',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 4'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	40','descrição produto 40',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 4'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	41','descrição produto 41',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 5'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	42','descrição produto 42',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 5'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	43','descrição produto 43',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 5'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	44','descrição produto 44',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 5'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	45','descrição produto 45',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 5'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	46','descrição produto 46',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 5'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	47','descrição produto 47',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 5'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	48','descrição produto 48',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 5'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	49','descrição produto 49',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 5'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	50','descrição produto 50',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 5'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	51','descrição produto 51',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 6'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	52','descrição produto 52',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 6'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	53','descrição produto 53',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 6'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	54','descrição produto 54',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 6'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	55','descrição produto 55',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 6'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	56','descrição produto 56',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 6'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	57','descrição produto 57',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 6'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	58','descrição produto 58',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 6'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	59','descrição produto 59',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 6'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	60','descrição produto 60',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 6'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	61','descrição produto 61',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 7'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	62','descrição produto 62',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 7'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	63','descrição produto 63',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 7'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	64','descrição produto 64',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 7'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	65','descrição produto 65',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 7'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	66','descrição produto 66',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 7'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	67','descrição produto 67',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 7'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	68','descrição produto 68',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 7'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	69','descrição produto 69',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 7'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	70','descrição produto 70',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 7'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	71','descrição produto 71',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 7'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	72','descrição produto 72',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 7'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	73','descrição produto 73',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 8'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	74','descrição produto 74',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 8'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	75','descrição produto 75',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 8'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	76','descrição produto 76',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 8'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	77','descrição produto 77',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 8'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	78','descrição produto 78',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 8'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	79','descrição produto 79',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 8'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	80','descrição produto 80',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 8'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	81','descrição produto 81',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 8'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	82','descrição produto 82',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 9'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	83','descrição produto 83',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 9'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	84','descrição produto 84',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 9'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	85','descrição produto 85',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 9'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	86','descrição produto 86',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 9'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	87','descrição produto 87',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 9'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	88','descrição produto 88',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 9'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	89','descrição produto 89',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 9'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	90','descrição produto 90',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 9'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	91','descrição produto 91',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 10'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	92','descrição produto 92',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 10'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	93','descrição produto 93',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 10'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	94','descrição produto 94',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 10'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	95','descrição produto 95',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 10'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	96','descrição produto 96',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 10'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	97','descrição produto 97',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 10'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	98','descrição produto 98',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 10'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	99','descrição produto 99',now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 10'));
INSERT INTO `hotmart_challenge`.`product`(`NAME`,`DESCRIPTION`,`CREATION_DATE`,`ID_PRODUCT_CATEGORY`) VALUES ('produto 	100','descrição produto 100'	,now(),(select id from `hotmart_challenge`.product_category where name like 'categoria 10'));

--CARGA INICIAL DE VENDEDORES
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Adelaide Quirino');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Agostinho Veríssimo');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Aguinaldo Milheirão');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Aluísio Sousa');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Amália Quintal');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Amélia Brandão');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Amélia Prado');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Ana Bulhões');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Anabela Fontes');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Anacleto Paranaguá');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Angelino Moreyra');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Arnaldo Dorneles');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Artur Henriques');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Astolfo Valim');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Bráulio Pessoa');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Brígida Robalinho');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Caetano Aldeia');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Carla Piteira');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Carolina Aquino');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Clementina Pérez');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Conrado Aragón');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Corina Carvalhosa');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Cosme Bento');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Cássia Gonçalves');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Cátia Bautista');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Damião Pinho');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Daniela Silva');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Danilo Tomé');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Derli Zarco');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Elvira Castello Branco');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Ema Casado');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Ema Câmara');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Emiliana Damásio');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Enilda Vilalobos');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Estêvão Ruas');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Eudes Farias');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Eunice Quinzeiro');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Eurico Moreira');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Fabiana Rocha');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Fabiana Vilela');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Fernanda Cerqueira');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Gabriel Trinidad');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Galindo Caiado');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Gaudêncio Estévez');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Gerardo Mendonça');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Greice Roriz');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Guaraci Bethancout');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Guido Lampreia');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Hermígio Pires');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Iberê Mansilla');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Isaac, Isaque Henriques');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Israel Candeias');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Ivete Leiria');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Jacinto Vicario');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Jacir Carreiro');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Jerónimo, Jerônimo Bairros');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Joaquim Sesimbra');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Josefa Rijo');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Jurema Esteves');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Justino Grilo');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Lavínia Mourato');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Levi Dias');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Leónidas Baião');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Luciana Taperebá');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Lázaro Brito');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Lídia Águeda');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Marcelo Canadas');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Mariana Peres');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Marisa Cotrim');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Maximiliano Hernández');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Natália Picanço');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Natália Saldanha');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Odilia Fortunato');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Oscar Cairu');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Palmiro Lousado');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Paraguaçu Suaçuna');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Pascoal Alencar');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Pascoal Rabello');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Quintiliana Gutiérrez');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Rogério Moura');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Rudá Álvaro');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Sabino Vilanova');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Salvador Suaçuna');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Sebastiana Ataí');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Sebastião Collaço');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Serafina Raminhos');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Severino Peláez');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Socorro Piñero');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Sílvia Parracho');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Tabalipa Bensaúde');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Taíssa Faia');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Tiago Gameiro');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Tobias Mattozo');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Ulrico Lobato');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Valmor Beiriz');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Valmor Valentín');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Virgília Soeiro');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Ágata Semedo');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Átila Sintra');
INSERT INTO `hotmart_challenge`.`salesman` (`NAME`) VALUES ('Óscar Noite');

-- CARGA INCIAL DE COMPRADORES
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Abílio Brasil');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Adosindo Francia');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Alexandra Brião');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Alípio Infante');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Andreia Jácome');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Aniano Espargosa');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Augusto Vicario');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Aurora Foquiço');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Bartira Valente');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Bernardete Morgado');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Carolina Doutel');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Caím Freyria');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Caím Gago');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Cesário Monjardim');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Clarindo Linares');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Cristina Hipólito');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Cássio Mattos');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('David Beça');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Denise Conde');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Denise Villena');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Deolindo Valentín');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Dinarte Brites');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Dinis Simón');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Dália Villalobos');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Eduarda Rijo');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Egas Cabeça de Vaca');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Elia Ferrão');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Elvira Telles');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Epifânia Quintanilha');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Esperança Aranha');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Esperança Lago');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Eugénio Pêssego');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Eusébio Veríssimo');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Eva Caeira');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Ezequiel Pitangui');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Fernanda Coito');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Filipa Leitão');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Flamínia Antunes');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Flamínia Laranjeira');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Fábia Meneses');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Genoveva Francia');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Gilberto Villas Bôas');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Gilda Malheiro');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Greice Parente');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Guilherme Capiperibe');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Herberto Paes');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Hermenegildo Mendonça');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Hermenegildo Morais');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Horácio Festas');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Horácio Zambujal');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Hélia Gouveia');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Inaiá Junquera');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Inês Negreiros');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Iolanda Ochoa');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Isaac, Isaque Paredes');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Iuri Mourão');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Jacinta Cortesão');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Jacir Modesto');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Jaime Pinheiro');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Jandaíra Guaraná');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Joel Chousa');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Jordão Telinhos');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Jurema Assumpção');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Lara Góis');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Leonor Aragón');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Liana Vila-Chã');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Lua Pino');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Ludovico Guerrero');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Lídia Garcés');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Lívia Mainha');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Manuel Cabeza de Vaca');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Mara Cortês');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Mara Lóio');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Marilda Figueira');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Milu Barbosa');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Miriam Cortesão');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Miru Moutinho');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Moacir Arruda');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Natacha Quintero');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Nicanor Passarinho');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Palmira Carvajal');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Querubim Vieyra');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Quintiliano Freiria');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Rafael Monjardim');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Renan Bezerril');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Renan Meira');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Samuel Alvarenga');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Samuel Maia');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Sofia Tigre');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Telmo Parracho');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Tibúrcio Póvoas');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Udo Pinhal');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Urbano Macedo');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Valentina Casalinho');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Valentina Lameiras');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Vanderlei González');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Violeta Canhão');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Xavier Leça');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Xénia Becerril');
INSERT INTO `hotmart_challenge`.`buyer` (`NAME`) VALUES ('Zuriel Fragoso');